"""add created_at to fields

Revision ID: 11308a4c3328
Revises: 3ffbb5e883cd
Create Date: 2026-04-09 19:08:49.691006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11308a4c3328'
down_revision: Union[str, Sequence[str], None] = '3ffbb5e883cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'created_at')
    # ### end Alembic commands ###
